"""create user_address table

Revision ID: b6b53feef39f
Revises: b76af0c1ef8b
Create Date: 2023-08-17 01:05:56.339739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b53feef39f'
down_revision: Union[str, None] = 'b76af0c1ef8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('address_line_1', sa.String(length=256), nullable=False),
                    sa.Column('address_line_2', sa.String(length=256), nullable=True),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('postal_code', sa.Integer(), nullable=False),
                    sa.Column('telephone_number', sa.Integer(), nullable=False),
                    sa.Column('mobile', sa.Integer(), nullable=True),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_address_id'), 'user_address', ['id'], unique=False)
    op.create_index(op.f('ix_user_address_user_id'), 'user_address', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_address_user_id'), table_name='user_address')
    op.drop_index(op.f('ix_user_address_id'), table_name='user_address')
    op.drop_table('user_address')
    # ### end Alembic commands ###
